# Generated by Django 5.2 on 2025-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resetpasswordlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordlink',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
