# Generated by Django 5.2 on 2025-04-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzle', '0007_puzzlequestionhint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('puzzle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.puzzle')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='easy', max_length=20)),
                ('daily_date', models.DateField(auto_now_add=True, verbose_name='Challenge Date')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='Challenge Theme')),
            ],
            bases=('puzzle.puzzle',),
        ),
    ]
