# Generated by Django 5.2 on 2025-04-18 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='daily_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Challenge Date'),
        ),
    ]
