# Generated by Django 5.2 on 2025-04-20 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_alter_dailychallenge_daily_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='daily_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Challenge Date'),
        ),
    ]
