# Generated by Django 5.2 on 2025-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_dailychallenge_daily_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='theme',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Challenge Theme'),
        ),
    ]
