# Generated by Django 5.2 on 2025-04-13 01:06

import django.db.models.deletion
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('encrypted_message', models.TextField()),
                ('one_time_view', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=False)),
                ('self_destruct_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.query.QuerySet, related_name='puzzles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('solution', models.TextField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='puzzle.puzzle')),
            ],
        ),
    ]
