# Generated by Django 5.2 on 2025-04-13 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puzzlequestions',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='puzzle.puzzle'),
        ),
    ]
