# Generated by Django 5.2 on 2025-04-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_alter_puzzle_created_by_alter_puzzlequestions_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='nonce',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='salt',
            field=models.TextField(default=''),
        ),
    ]
