# Generated by Django 5.2 on 2025-04-14 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_alter_puzzle_id_alter_puzzlequestions_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuzzleQuestions',
            new_name='PuzzleQuestion',
        ),
        migrations.CreateModel(
            name='PuzzleSolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_puzzles', to='puzzle.puzzle')),
                ('solved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_puzzles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
